version: '3.4'

services: 
  cumplidos_crud_api:

    image: golang:1.15-alpine
    container_name: ${API_NAME}
    volumes:
      - go_src:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    environment:
      - GO111MODULE=on
    env_file: 
      - .env
    ports: 
      - "${REVISION_CUMPLIDOS_PROOVEDORES_CRUD_HTTP_PORT}:${REVISION_CUMPLIDOS_PROOVEDORES_CRUD_HTTP_PORT}"  
    working_dir: /go/src
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -u github.com/beego/bee ;go get -v -u ./...; pwd;go mod init; bee run -downdoc=true -gendoc=true'

  data_base:
    container_name: ${REVISION_CUMPLIDOS_PROOVEDORES_CRUD_PGDB}
    image: postgres:10.15-alpine
    volumes: 
        - postgres_data:/var/lib/postgresql/data
    ports: 
        - "${REVISION_CUMPLIDOS_PROOVEDORES_CRUD_PGPORT}:${REVISION_CUMPLIDOS_PROOVEDORES_CRUD_PGPORT}"        
    env_file: 
        - .env



volumes:
  go_src:
  postgres_data: